# This is a general use makefile for robotics cape projects written in C.
# Just change the target name to match your main source code filename.
TARGET = rc_balance

PKG_CFLAGS=$(shell pkg-config libevdev --cflags)
PKG_LIBS=$(shell pkg-config libevdev --libs)

include ../robotics.mk 

